# Generated by Django 4.2.5 on 2023-10-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='id_code',
            field=models.IntegerField(unique=True),
        ),
    ]
